CREATE DATABASE IF NOT EXISTS MovieDB;
USE MovieDB;

CREATE TABLE IF NOT EXISTS movies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS images (
    id INT PRIMARY KEY AUTO_INCREMENT,
    image_url VARCHAR(255) NOT NULL,
    movie_id INT NOT NULL UNIQUE,
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
);
