name: Build and Deploy Next.js App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: https://moviehorizon.fun
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          use_insecure_cipher: true
          source: "out/*"
          target: "/home/u451682670/public_html/"
          timeout: 60s
          strip_components: 1
          debug: true

      - name: Setup server environment and start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          script: |
            # Check if directory exists, if not create it
            mkdir -p /home/u451682670/moviehorizon.fun/server

            # Deploy server files (assuming they're in a 'server' directory in your repo)
            # If your server files are elsewhere, adjust this part

            # Navigate to server directory
            cd /home/u451682670/moviehorizon.fun/server

            # Check if Node.js is installed, if not use NVM to install
            if ! command -v node &> /dev/null; then
              echo "Node.js not found, installing via NVM..."
              # Install NVM
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              # Install Node.js
              nvm install 18
              nvm use 18
            fi

            # Install dependencies
            npm install

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found, installing..."
              npm install -g pm2
            fi

            # Start or restart the server
            pm2 restart server.js || pm2 start server.js --name "movie-api"
