name: Direct File Upload Test

on:
  workflow_dispatch:

jobs:
  test-file-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: |
          echo "<html><body><h1>Test File</h1><p>This is a test file uploaded at $(date)</p></body></html>" > test.html
          echo "Test file created:"
          cat test.html

      - name: Check Hostinger directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          script: |
            echo "Checking public_html directory permissions:"
            ls -la /home/u451682670/
            ls -la /home/u451682670/public_html/
            echo "Who am I and what are my permissions:"
            whoami
            id

      - name: Upload directly via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          script: |
            echo "<html><body><h1>Test File Created on Server</h1><p>This is a test file created directly on the server at $(date)</p></body></html>" > /home/u451682670/public_html/test-direct.html
            echo "File created:"
            ls -la /home/u451682670/public_html/test-direct.html

      - name: Upload test file using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          source: "test.html"
          target: "/home/u451682670/public_html/"
          debug: true

      - name: Verify file upload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 65002
          script: |
            echo "Checking for uploaded test file:"
            ls -la /home/u451682670/public_html/test.html || echo "test.html not found!"
            ls -la /home/u451682670/public_html/test-direct.html || echo "test-direct.html not found!"
            echo "Contents of public_html directory:"
            ls -la /home/u451682670/public_html/
